site_name: Centre for Imaging Research (CIR)

repo_url: https://github.com/k-CIR/cir-wiki
repo_name: Show on GitHub
edit_uri: blob/dev/docs/
site_url: https://www.kcir.se
watch:
  - docs
  - mkdocs.yml

theme: 
  name: material
  logo: assets/logo_white.svg
  color_mode: auto
  # user_color_mode_toggle: true
  palette:
    # - media: "(prefers-color-scheme)"
    #   primary: black
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
      - announce.dismiss
      - content.action.view
      - content.action.edit
      - navigation.instant
      - navigation.instant.preview
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.path
      - navigation.indexes
      - toc.integrate
      - navigation.footer
      - content.code.copy
      - navigation.sections # Makes top level sections expandable

extra_css:
  - assets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
        toc_depth: 2
  - attr_list
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.tab:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.blocks.caption
validation:
  links:
    absolute_links: relative_to_docs
plugins:
  - search
  - include_dir_to_nav:
      # add _dep_ beginning of filename to ignore it in nav
      file_pattern: '^(?!.*_dep*)' 
  - macros
  - drawio
extra:
  picture_path: /resources/wiki_images
  manuals_path: /resources/manuals

nav:
  - Home: 
    - index.md
    - How to edit this wiki: edit-this-wiki.md
    - Contribute to this wiki: contribute-to-wiki.md
  - NatMEG: 
    - natmeg/index.md
    - Preparation: natmeg/preparation/
    - SQUID Acquisition: 
      - natmeg/squid-acquisition/index.md
      - natmeg/squid-acquisition/
    - OPM Acquisition: natmeg/opm-acquisition/
    - Stimulus Equipment:
      - Audio: natmeg/stimulus-equipment/audio
      - Visual: natmeg/stimulus-equipment/visual
      - Other: natmeg/stimulus-equipment/other
    - Response Equipment: natmeg/response-equipment/
    - Presentation: natmeg/presentation/
    - Preprocessing:
      - Using the GUI: natmeg/preprocessing/config_gui.md
      - Pipeline: natmeg/preprocessing/pipeline.md
      # https://github.com/k-CIR/NatMEG-utils/blob/main/README.md
      - About MaxFilter: natmeg/preprocessing/maxfilter
    - Other: natmeg/other/
    - MEEG-analyis: 
      - natmeg/MEEG-analysis/index.md
      - Tips and tricks: natmeg/MEEG-analysis/tips-and-tricks/
    - NatMEG server (legacy):
      - natmeg/server/index.md
      - Set-up connection: natmeg/server/set-up-connection/
      - Install software: natmeg/server/install-software/
      - Script tips: natmeg/server/script-tips/
      - Troubleshooting: natmeg/server/troubleshooting/
    - Cerberos: natmeg/cerberos/
  - BMIC: 
    - BMIC: bmic/index.md
    - Getting Started: bmic/01_getting_started
    - Solena: bmic/02_solena
    - BIDS at BMIC: bmic/03_bmic_bids
  - MRC:
    - mrc/index.md
    - mrc/mrc-bids.md
    - mrc/mrc-cir-protocol.md
    # - mrc/mrc-cir-data-template.md
    - Response Equipment: 
        - mrc/response-equipment/
  #- Server:
   # - About the server: server/index.md
    #- Connect: server/connect/
    #- Installed software: server/install-software/
    #- BIDS:
    #  - BIDS at NatMEG: natmeg/bids/
    #  - BIDS at BMIC: bmic/03_bmic_bids
    #  - BIDS at MRC: mrc/mrc-bids.md
  - SPICE:
    - SPICE/index.md
    - How to connect: SPICE/01_how_to_connect.md
    - Best practices for using SPICE: SPICE/02_best_practice.md
    - Tips for using VScode: SPICE/03_Vscode_tips.md
    - Download your data: SPICE/04_download_your_data.md
    - BIDS: SPICE/05_spiceBIDS.md
    - Software:
      - Anaconda: SPICE/software/01_anaconda.md
      - FSL: SPICE/software/02_FSL.md
      - FreeSurfer: SPICE/software/03_freesurfer.md
      - Matlab: SPICE/software/04_Matlab.md
      - R: SPICE/software/05_R.md
    - Singularity containers:
      - SPICE/singularity_containers/index.md
      - fMRIPrep: SPICE/singularity_containers/01_fmriprep.md
      - Heudiconv: SPICE/singularity_containers/02_heudiconv.md
      - Halfpipe: SPICE/singularity_containers/03_halfpipe.md
      - MRIQC: SPICE/singularity_containers/04_mriqc.md
