site_name: Centre for Imaging Research (CIR)

repo_url: https://github.com/k-CIR/cir-wiki
repo_name: Show on GitHub
edit_uri: blob/main/docs/
site_url: https://www.kcir.se

theme: 
  name: material
  logo: assets/logo_white.svg
  color_mode: auto
  # user_color_mode_toggle: true
  palette:
    # - media: "(prefers-color-scheme)"
    #   primary: black
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
      - announce.dismiss
      - content.action.view
      - content.action.edit
      - navigation.instant
      - navigation.instant.preview
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.path
      - navigation.indexes
      - toc.follow
      - navigation.footer
      # - navigation.sections # Makes top level sections expandable
markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.tab:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
plugins:
  - search
  - include_dir_to_nav
  - macros
extra:
  # version:
  #   provider: mike
  picture_path: /docs/resources/wiki_images
  scope: /


nav:
  - Home: index.md
  - NatMEG: 
    - natmeg/index.md
    - Preparation: natmeg/preparation/
    - SQUID Acquisition: natmeg/squid-acquisition/
    - OPM Acquisition: natmeg/opm-acquisition/
    - Stimulus Equipment:
      - Audio: natmeg/stimulus-equipment/audio
      - Visual: natmeg/stimulus-equipment/visual
      - Other: natmeg/stimulus-equipment/other
    - Response Equipment: natmeg/response-equipment/
    - Presentation: natmeg/presentation/
    - Other: natmeg/other/
    - NatMEG server:
      - Set-up connection: natmeg/server/set-up-connection/
      - Install software: natmeg/server/install-software/
      - Script tips: natmeg/server/script-tips/
      - Troubleshooting: natmeg/server/troubleshooting/
    - Cerberos: natmeg/cerberos/
  - BMIC: 
    - bmic/index.md
  - MRC:
    - mrc/index.md
    - mrc/mrc-cir-protocol.md
    - Response Equipment: 
        - Eye-tracker: mrc/response-equipment/
  - Server:
    - About the server: server/index.md
    - Connect: server/connect/
  
